name: Deploy Application

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  Build-Android:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
          dir: ${{ runner.temp }}

      - name: Install NDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platforms;android-33 ndk;25.2.9519653"

      - name: Compile Application
        shell: bash
        run: |
          cmake -B build_dir -S . \
            -DCMAKE_BUILD_TYPE=Debug \
            -DANDROID_ABI=arm64-v8a
          cmake --build build_dir --target amnezia
          mkdir -p output_apk
          find build_dir -name "*.apk" -exec cp {} output_apk/ \;

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Amnezia-APK
          path: output_apk/
          retention-days: 7
