name: Deploy Application

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  Build-Android:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platforms;android-33 build-tools;33.0.2"

      - name: Assemble Unsigned APK via Gradle
        run: |
          # Заходим напрямую в папку Android-клиента, минуя капризный CMake и Conan
          cd client/android || cd android || cd platforms/android || true
          
          # Даем права на запуск стандартному сборщику Google
          chmod +x gradlew || true
          
          # Запускаем сборку обычного отладочного APK без проверок подписи
          ./gradlew assembleDebug --no-daemon

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Amnezia-APK
          path: |
            **/*.apk
          retention-days: 7
