name: Deploy Application

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  Build-Android:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.7.3'
          host: 'linux'
          target: 'android'
          arch: 'android_arm64_v8a'
          dir: ${{ runner.temp }}

      - name: Install NDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platforms;android-33 ndk;25.2.9519653"

      - name: Compile Application
        shell: bash
        run: |
          # Разрешаем запуск скрипта сборки Amnezia
          chmod +x deploy/build.sh
          
          # Запускаем сборку под одну архитектуру БЕЗ отправки пакетов в сеть и БЕЗ подписи ключами
          # Флаг --abi arm64-v8a заставит conan работать только локально
          deploy/build.sh -t android --abi arm64-v8a
          
          # Создаем папку и собираем туда готовый APK-файл
          mkdir -p output_apk
          find deploy/build -name "*.apk" -exec cp {} output_apk/ \;
